source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'mysql2', '~> 0.2.6'
gem 'paperclip'
gem 'rspec-rails'
gem 'rmagick'
gem 'devise'
gem 'jquery-rails'
gem 'heroku'
gem "paperclipdropbox", '1.0.5'
gem 'factory_girl_rails'
